### ISSUE TITLE
Yazar rozet ve seçilmiş rozetleri

### ISSUE THREAD

**Issue by maidis** [beucismis/limoon#2]
Merhaba,

Aklımdaki birkaç kaydı daha ara ara gireceğim. Projede yer almasının iyi olacağını düşündükleriniz kalabilir, diğerlerini kapatabilirsiniz. Açık kalanları da, siz, diğer katkıcılar veya ben zamanla gerçekleştiririz.

https://eksisozluk.com/rozetler/kullanıcı_adı sayfasında badge-icons-container div'i altındaki selected-badge-item ve data-owned bunun için kullanılabilir sanırım.

**Comment by beucismis** [comment]
Merhaba, fikir için teşekkürler. PR: 67610c025b030b5bb3330f780180731024422344
